# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdPlaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=15)),
            ],
        ),
    ]
