# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BdPlaces', '0002_subplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='division',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to='BdPlaces.Place'),
        ),
    ]
