# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdPlaces', '0003_auto_20171026_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='division',
            field=models.CharField(max_length=15),
        ),
    ]
