# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BdPlaces', '0004_auto_20171026_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplace',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BdPlaces.Place'),
        ),
    ]
