# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BdPlaces', '0005_auto_20171026_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplace',
            name='foreign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BdPlaces.Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subplace',
            name='district',
            field=models.CharField(max_length=15),
        ),
    ]
